# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokerRoyaleRivals' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokerRoyaleRivals
pod 'IQKeyboardManagerSwift'
  pod 'Adjust','4.38.4'

end
